inputFilePath = "../input/guitar.wav"
outputFilePath = "../output/guitarNew.wav"
sampleRate = 48000.0  # hertz
noiseLen = 0.01       # seconds
noiseAmplitude = 0.1
startOffset = 1       # seconds
startFreqCodingRange = 21000
endFreqCodingRange = 25000
scanWindow = noiseLen
freqGranularity = 8  # power of 2
defaultStegoFileDuration = 5 # seconds